### ISSUE TITLE
Есть проблема.

### ISSUE THREAD

**Issue by kramber1024** [LaryStef/Algorithms#2]
Зачем ты сортируешь стек? Это не имеет ни какого смысла. Пожалуйста, хватит.

**Comment by LaryStef** [comment]
Я знаю, что я делаю. Это принесёт пользу человечеству. Если не в этом тысячелетии, так в следующем. У каждого из нас свой собственный путь, я приношу и буду приносить человечеству максимум пользы, а ты можешь делать так, как пожелаешь нужным

UPD: не нашел, как сделать реплай

**Comment by kramber1024** [comment]
Спасибо за ваш драгоценнейший ответ, закрываю issue, проблема решена
